name: Postman API Tests in CLI

on:
  workflow_dispatch:

jobs:
  run-postman-tests-in-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/unix.sh" | sh
          postman --version

      - name: Login Postman
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
        run: postman login --with-api-key "$POSTMAN_API_KEY"

      - name: Run Postman Collection
        env:
          AMADEUS_CLIENT_ID: ${{ secrets.AMADEUS_CLIENT_ID }}
          AMADEUS_CLIENT_SECRET: ${{ secrets.AMADEUS_CLIENT_SECRET }}
        run: |
          postman collection run "48793988-c7241c38-56ac-4168-a6eb-666b471e90df" \
            --environment "48793988-33f72e9d-e71e-4a14-8fcc-91cc00c21372" \
            --env-var AMADEUS_ID="$AMADEUS_CLIENT_ID" \
            --env-var AMADEUS_SECRET="$AMADEUS_CLIENT_SECRET"
