name: Postman API Tests

on:
  workflow_dispatch:

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Postman CLI
        run: |
          npm install -g @postman/cli
          postman login --with-api-key ${{ secrets.POSTMANAPI_KEY }}

      - name: Run Postman Collection
        run: postman collection run "6d32ae4a-8314-4e99-8d82-985a19c56633" --environment "48793988-96457a37-d3c8-4732-a703-fb2e6d0ad415"
        env:
          POSTMANAPI_KEY: ${{ secrets.POSTMANAPI_KEY }}
